import type { ILanguage } from './lang/type';

export const itemsSource: Record<keyof ILanguage['items'], 'auction' | 'bazaar' | 'vendor'> = {
  'Amber Material': 'auction',
  'Amber-polished Drill Engine': 'auction',
  'Ammonite Pet': 'auction',
  BIOFUEL: 'vendor',
  BROWN_MUSHROOM: 'bazaar',
  'Beacon I': 'auction',
  'Beacon II': 'auction',
  'Beacon III': 'auction',
  'Beacon IV': 'auction',
  'Beacon V': 'auction',
  'Bejeweled Handle': 'auction',
  'Blue Cheese Goblin Omelette': 'auction',
  'Boots Of Divan': 'auction',
  CACTUS: 'bazaar',
  CARROT_ITEM: 'bazaar',
  COMPOST: 'bazaar',
  'Cactus Green': 'auction',
  'Chestplate Of Divan': 'auction',
  'Control Switch': 'auction',
  Corleonite: 'auction',
  DIAMONITE: 'bazaar',
  Dandelion: 'auction',
  'Divan Fragment': 'auction',
  "Divan's Alloy": 'auction',
  "Divan's Drill": 'auction',
  'Drill Engine': 'auction',
  ENCHANTED_BAKED_POTATO: 'bazaar',
  ENCHANTED_BREAD: 'bazaar',
  ENCHANTED_BROWN_MUSHROOM: 'bazaar',
  ENCHANTED_CACTUS: 'bazaar',
  ENCHANTED_CACTUS_GREEN: 'bazaar',
  ENCHANTED_CARROT: 'bazaar',
  ENCHANTED_COAL_BLOCK: 'bazaar',
  ENCHANTED_COBBLESTONE: 'bazaar',
  ENCHANTED_COCOA: 'bazaar',
  ENCHANTED_DIAMOND_BLOCK: 'bazaar',
  ENCHANTED_ENDER_PEARL: 'bazaar',
  ENCHANTED_GOLD: 'bazaar',
  ENCHANTED_GOLD_BLOCK: 'bazaar',
  ENCHANTED_HAY_BLOCK: 'bazaar',
  ENCHANTED_HUGE_MUSHROOM_1: 'bazaar',
  ENCHANTED_HUGE_MUSHROOM_2: 'bazaar',
  ENCHANTED_IRON_BLOCK: 'bazaar',
  ENCHANTED_MELON: 'bazaar',
  ENCHANTED_MELON_BLOCK: 'bazaar',
  ENCHANTED_MITHRIL: 'bazaar',
  ENCHANTED_NETHER_STALK: 'bazaar',
  ENCHANTED_PAPER: 'bazaar',
  ENCHANTED_POTATO: 'bazaar',
  ENCHANTED_PUMPKIN: 'bazaar',
  ENCHANTED_REDSTONE_BLOCK: 'bazaar',
  ENCHANTED_RED_MUSHROOM: 'bazaar',
  ENCHANTED_SUGAR: 'bazaar',
  ENCHANTED_SUGAR_CANE: 'bazaar',
  ENCHANTED_TITANIUM: 'bazaar',
  'Electron Transmitter': 'auction',
  'Enchanted Poisonous Potato': 'auction',
  FINE_AMBER_GEM: 'bazaar',
  FINE_AMETHYST_GEM: 'bazaar',
  FINE_JADE_GEM: 'bazaar',
  FINE_RUBY_GEM: 'bazaar',
  FINE_SAPPHIRE_GEM: 'bazaar',
  FINE_TOPAZ_GEM: 'bazaar',
  FLAWED_RUBY_GEM: 'bazaar',
  FLAWLESS_AMBER_GEM: 'bazaar',
  FLAWLESS_JASPER_GEM: 'bazaar',
  FLAWLESS_RUBY_GEM: 'bazaar',
  FLAWLESS_TOPAZ_GEM: 'bazaar',
  'FTX 3070': 'auction',
  'Fuel Tank': 'auction',
  GOBLIN_EGG: 'bazaar',
  GOBLIN_EGG_BLUE: 'bazaar',
  GOBLIN_EGG_GREEN: 'bazaar',
  GOBLIN_EGG_RED: 'bazaar',
  GOBLIN_EGG_YELLOW: 'bazaar',
  'Gemstone Chamber': 'auction',
  'Gemstone Drill LT-522': 'auction',
  'Gemstone Fuel Tank': 'auction',
  'Gemstone Mixture': 'auction',
  'Glacite Jewel': 'auction',
  'Goblin Omelette': 'auction',
  'Golden Plate': 'auction',
  HARD_STONE: 'bazaar',
  HAY_BLOCK: 'bazaar',
  HUGE_MUSHROOM_1: 'bazaar',
  HUGE_MUSHROOM_2: 'bazaar',
  Helix: 'auction',
  'Helmet Of Divan': 'auction',
  'Hot Stuff': 'auction',
  'INK_SACK:3': 'bazaar',
  'Jasper Drill X': 'auction',
  'Leggings Of Divan': 'auction',
  MELON: 'bazaar',
  MELON_BLOCK: 'bazaar',
  MITHRIL_ORE: 'bazaar',
  MUTANT_NETHER_STALK: 'bazaar',
  'Magma Core': 'vendor',
  'Mithril Drill SX-R226': 'auction',
  'Mithril Drill SX-R326': 'auction',
  'Mithril Pickaxe': 'auction',
  'Mithril Plate': 'auction',
  'Mithril-Infused Fuel Tank': 'auction',
  'Mithril-Plated Drill Engine': 'auction',
  NETHER_STALK: 'bazaar',
  'Oil Barrel': 'auction',
  PERFECT_SAPPHIRE_GEM: 'bazaar',
  PLASMA_BUCKET: 'bazaar',
  POLISHED_PUMPKIN: 'bazaar',
  POTATO_ITEM: 'bazaar',
  POWER_CRYSTAL: 'bazaar',
  PUMPKIN: 'bazaar',
  'Perfectly-Cut Fuel Tank': 'auction',
  'Pesto Goblin Omelette': 'auction',
  'Petrified Starfall': 'auction',
  'Poisonous Potato': 'auction',
  Poppy: 'auction',
  'Pure Mithril': 'auction',
  RED_MUSHROOM: 'bazaar',
  REFINED_DIAMOND: 'bazaar',
  REFINED_MITHRIL: 'bazaar',
  REFINED_TITANIUM: 'bazaar',
  ROUGH_AMBER_GEM: 'bazaar',
  'Refined Mithril Pickaxe': 'auction',
  'Robotron Reflector': 'auction',
  'Rock Gemstone': 'auction',
  'Ruby Drill TX-15': 'auction',
  'Ruby-polished Drill Engine': 'auction',
  SLUDGE_JUICE: 'bazaar',
  STARFALL: 'bazaar',
  SUGAR_CANE: 'bazaar',
  'Sapphire-polished Drill Engine': 'auction',
  'Spicy Goblin Omelette': 'auction',
  'Sunny Side Goblin Omelette': 'auction',
  'Superlite Motor': 'auction',
  'Synthetic Heart': 'auction',
  TITANIUM_ORE: 'bazaar',
  TREASURITE: 'bazaar',
  'Titanium Artifact': 'auction',
  'Titanium Drill DR-X355': 'auction',
  'Titanium Drill DR-X455': 'auction',
  'Titanium Drill DR-X555': 'auction',
  'Titanium Drill DR-X655': 'auction',
  'Titanium Relic': 'auction',
  'Titanium Ring': 'auction',
  'Titanium Talisman': 'auction',
  'Titanium-Infused Fuel Tank': 'auction',
  'Titanium-Plated Drill Engine': 'auction',
  'Topaz Drill KGR-12': 'auction',
  'Travel Scroll to the Crystal Hollows': 'auction',
  'Travel Scroll to the Dwarven Forge': 'auction',
  Volta: 'auction',
  WHEAT: 'bazaar',
  WORM_MEMBRANE: 'bazaar',
  coins: 'vendor'
};

export const itemsVendorPrice: Partial<Record<keyof ILanguage['items'], number>> = {
  BIOFUEL: 20000,
  'Magma Core': 0,
  coins: 1
};
