const auctionItems = [
  'Amber-polished Drill Engine',
  'Amber Crystal',
  'Amber Necklace',
  'Amethyst Crystal',
  'Amethyst Gauntlet',
  'Ammonite Pet',
  'Ankylosaurus Pet',
  'Aquamarine Crystal',
  'Artifact Of Power',
  'Beacon I',
  'Beacon II',
  'Beacon III',
  'Beacon IV',
  'Beacon V',
  'Bejeweled Collar',
  'Blue Cheese Goblin Omelette',
  'Boots Of Divan',
  'Chestplate Of Divan',
  'Citrine Crystal',
  'Claw Fossil',
  'Clubbed Fossil',
  "Divan's Alloy",
  "Divan's Drill",
  'Dwarven Handwarmers',
  'Dwarven Metal Talisman',
  'Footprint Fossil',
  'Gemstone Chamber',
  'Gemstone Drill LT-522',
  'Gemstone Fuel Tank',
  'Glacite-Plated Chisel',
  'Goblin Omelette',
  'Goblin Pet',
  'Helix Fossil',
  'Helmet Of Divan',
  'Jade Belt',
  'Jade Crystal',
  'Jasper Crystal',
  'Jasper Drill X',
  'Leggings Of Divan',
  'Mammoth Pet',
  'Mithril-Infused Fuel Tank',
  'Mithril-Plated Drill Engine',
  'Mithril Belt',
  'Mithril Cloak',
  'Mithril Drill SX-R226',
  'Mithril Drill SX-R326',
  'Mithril Gauntlet',
  'Mithril Necklace',
  'Mole Pet',
  'Onyx Crystal',
  'Opal Crystal',
  'Pendant Of Divan',
  'Penguin Pet',
  'Perfect Chisel',
  'Perfectly-Cut Fuel Tank',
  'Peridot Crystal',
  'Pesto Goblin Omelette',
  'Polished Topaz Rod',
  'Portable Campfire',
  'Reinforced Chisel',
  'Relic Of Power',
  'Ruby-polished Drill Engine',
  'Ruby Crystal',
  'Ruby Drill TX-15',
  'Sapphire-polished Drill Engine',
  'Sapphire Cloak',
  'Sapphire Crystal',
  'Shattered Locket',
  'Spicy Goblin Omelette',
  'Spine Fossil',
  'Spinosaurus Pet',
  'Starfall Seasoning',
  'Sunny Side Goblin Omelette',
  'T-Rex Pet',
  'Titanium-Infused Fuel Tank',
  'Titanium-Plated Drill Engine',
  'Titanium Artifact',
  'Titanium Belt',
  'Titanium Cloak',
  'Titanium Drill DR-X355',
  'Titanium Drill DR-X455',
  'Titanium Drill DR-X555',
  'Titanium Drill DR-X655',
  'Titanium Gauntlet',
  'Titanium Necklace',
  'Titanium Relic',
  'Titanium Ring',
  'Titanium Talisman',
  'Topaz Crystal',
  'Topaz Drill KGR-12',
  'Travel Scroll to the Dwarven Base Camp',
  'Travel Scroll to the Dwarven Forge',
  'Tungsten Regulator',
  'Tusk Fossil',
  'Ugly Fossil',
  'Webbed Fossil'
];

export const forge = { auctionItems };
